### ISSUE TITLE
missing readme

### ISSUE THREAD

**Issue by awdwad45456** [ArchyInUse/SausageChat#1]

**Comment by ArchyInUse** [comment]
We're going to create a ReadMe soon, the program infastructure changed quite alot over the course of time and thus we've decided to make the ReadMe when the messaging itself works, which is very close to being done.
I'll close the issue once we've created a ReadMe.

**Comment by ArchyInUse** [comment]
We've added a readme, we apologize for the wait but due to exams, I couldn't of worked on the project as much as I did in the beggining.
